# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('press', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('pages', models.IntegerField()),
                ('ISBN', models.CharField(max_length=15)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('MALE', '男'), ('FEMALE', '女'), ('OTHER', '其他'), ('SECRET', '保密')], default='SECRET', max_length=2)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookInformationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('people_count', models.IntegerField()),
                ('start_rate_five', models.FloatField()),
                ('start_rate_four', models.FloatField()),
                ('start_rate_three', models.FloatField()),
                ('start_rate_two', models.FloatField()),
                ('start_rate_one', models.FloatField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.BookInformationSource')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book.BookAuthor'),
        ),
        migrations.AddField(
            model_name='book',
            name='scores',
            field=models.ManyToManyField(to='book.BookScore'),
        ),
        migrations.AddField(
            model_name='book',
            name='sources',
            field=models.ManyToManyField(to='book.BookInformationSource'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='book.BookTag'),
        ),
    ]
