# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170316_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(null=True, upload_to='book/image/%Y/%m/%d/'),
        ),
    ]
