# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
