# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, to='book.BookAuthor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='scores',
            field=models.ManyToManyField(null=True, to='book.BookScore'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sources',
            field=models.ManyToManyField(null=True, to='book.BookInformationSource'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(null=True, to='book.BookTag'),
        ),
    ]
