# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170425_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
