# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170425_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookscore',
            name='source',
        ),
    ]
