# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_bookscore_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookscore',
            old_name='start_rate_five',
            new_name='star_rate_five',
        ),
        migrations.RenameField(
            model_name='bookscore',
            old_name='start_rate_four',
            new_name='star_rate_four',
        ),
        migrations.RenameField(
            model_name='bookscore',
            old_name='start_rate_one',
            new_name='star_rate_one',
        ),
        migrations.RenameField(
            model_name='bookscore',
            old_name='start_rate_three',
            new_name='star_rate_three',
        ),
        migrations.RenameField(
            model_name='bookscore',
            old_name='start_rate_two',
            new_name='star_rate_two',
        ),
    ]
