# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20170425_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_five',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_four',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_one',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_three',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_two',
            field=models.CharField(max_length=10),
        ),
    ]
