# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170425_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscore',
            name='people_count',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
