# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20170425_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='people_count',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_five',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_four',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_one',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_three',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookscore',
            name='score_rate_two',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
