# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20170425_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book.BookAuthor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='scores',
            field=models.ManyToManyField(to='book.BookScore'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sources',
            field=models.ManyToManyField(to='book.BookInformationSource'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='book.BookTag'),
        ),
    ]
