# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(to='book.Book'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='pic',
            field=models.CharField(default='no-pic.jpg', max_length=200, null=True),
        ),
    ]
