# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20170513_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, null=True)),
                ('obj_id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
