# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_scrapytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
