# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_booklist_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookinformationsource',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
