# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20170604_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilduser',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
