# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_wilduser_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=500, verbose_name='评语')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookTag')),
            ],
        ),
    ]
