# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_auto_20170605_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.WildUser'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
