# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20170606_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
