# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_book_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
