# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_book_author_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='book.BookTag'),
        ),
    ]
