# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_auto_20170606_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_intro',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
