# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_auto_20170606_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
    ]
