# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_auto_20170608_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_intro',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bookremark',
            name='content',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='评语'),
        ),
    ]
