# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('book', '0039_auto_20170608_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilduser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='WildUser',
        ),
    ]
